---
- hosts: cat9k_2
  gather_facts: no
  connection: netconf
  remote_user: cisco
 
  tasks:
  - name: establish subscription
    netconf_config:
      xml: |
        <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
          <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
            <interface>
              <name>TenGigabitEthernet1/0/24</name>
              <description>tested by ansible</description>
              <enabled>true</enabled>
            </interface>
          </interfaces>
        </config>